# hwllo github action

name: hello world
on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Github action Hello, world!"

      - name: Say hello again
        run: echo "Github action: Hello, world again!"

