name: Deployment CI Pipeline
on:
  push:
    branches: main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  deploy-for-testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "16"

    - name: Install dependencies
      run: yarn

    - name: check style
      run: yarn eslint

    - name: build production
      run: yarn build

    - name: run tests
      run: yarn test

    - name: e2e tests
      uses: cypress-io/github-action@v5
      with:
        command: yarn test:e2e
        start: yarn start-prod
        wait-on: http://localhost:5000        

    - name: Prepare Fly.io
      #This action installs and configures the flyctl command-line tool, which is used to interact with Fly.io.
      uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only --config fly.toml --env "TIMESTAMP=$(date +%Y%m%d%H%M%S)"
      env:
        #allowing flyctl to authenticate with your Fly.io account.
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
