name: Deployment CI Pipeline
on:
  push:
    branches: main
  #pull_request:
   # branches: [ "main" ]
jobs:
  deploy-for-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "16"

    - name: Install dependencies
      run: yarn
    - run: echo "npm installed properly :-)"
    - name: check style
      run: yarn eslint
    
    
