name: CI Pipeline / NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  # A pull_request:
    # branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Build
      run: |
        npm install
    - run: echo "npm installed properly :-)"