name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

      - name: commit messages string
        env: 
          msg_str: ${{join(github.event.commits.*.message, 'opop')}}
        run: echo "$msg_str"

      - name: skip or not
        #if: ${{ contains(msg-str, 'skip') }}
        #if: ${{ contains(COMMIT_MESSAGES, 'skip') }}
        run: echo "Yes this skipped"  