name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

      - name: join commit messages
        id: jcm
        env: 
          msg0: ${{ toJson(github.event.commits.*.message) }}
          #msg1: ${{ toJson(env.msg0) }}
          #msg2: ${{ env.msg1[0] }}
        run: |
         echo "Joined commit messages:$msg0"
         echo "Joined commit messages:$msg1"
         echo "Joined commit messages:$msg2"

         #echo "::set-output name=msg::$msg1" 

      - name: Should Skip
        env:
          should_skip: ${{ contains(steps.jcm.outputs.msg, 'skip') }}
        run: echo "$should_skip, ${{toJson(steps.jcm.outputs.msg)}}"
        #run: echo 'HI ${{toJson(env)}}'
        #if: ${{ contains(github.event.commits.*.message, 'skip')  }}
        #run:  echo "skipp found"  

      - name: skip or not
        #if: ${{ contains(github.event.commits.*.message, 'skip')  }}
        #if: ${{ contains(msg_str, 'skipp') }}
        #if: ${{ contains(COMMIT_MESSAGES, 'skip') }}
        run: |
         echo "Yes this skipped"  
         echo "hello $msg_str"
         echo $msg_str