name: Print GitHub Action Variables

on:
  push:
    branches: main
  pull_request:
    branches: [main]

jobs:
  print-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Print Workflow Variables
        run: |
          echo "[GITHUB.EVENT_NAME:${{GITHUB.EVENT_NAME}}]"
          echo "[github.event.pull_request.status:${{ github.event.pull_request.status }}]"
          echo "[Repos Name, github.repository:${{ github.repository }}]"
          echo "[Triggering Branch, github.ref:${{github.ref}}]"
          echo "[Source Branch, github.event.pull_request.head.label:${{ github.event.pull_request.head.label }}]"
          echo "[Destination(base) branch, github.event.pull_request.base.label:${{ github.event.pull_request.base.label }}]"
      - name: PR object
        run: echo "Pull Request Object:${{ toJson(github.event.pull_request) }}"
